---
title: "Untitled"
author: "Guilherme Oliveira Casagrande"
date: "2023-12-04"
output: word_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(ggplot2)   # Fazer gráficos
library(GGally)    # Novo: análise de correlação
library(car)       # Novo: Indica a presença de multicolinearidade (calculo do VIF)
library(MASS)      # Novo: Selecionar variáveis
library(lmtest)    # Novo: Testes específicos de regressão
library(readxl)
library(dplyr)
library(RColorBrewer)
library(viridis)

opts_chunk$set(echo = TRUE)

fonte <- read.csv("fonte.csv", sep = ";")
```


## Regressão linear

## Preparação dos dados

```{r, message = FALSE, warning = FALSE, echo=FALSE}
dados = fonte[,1:8] %>% filter(source == 'vivareal') %>% drop_na()

dados$source_id = NULL
dados$timestamp = NULL
dados$source = NULL
```


## Etapa descritiva
```{r, message = FALSE, warning = FALSE, echo=FALSE}
ggpairs(dados)
```


```{r, message = FALSE, warning = FALSE, echo=FALSE}
modelo1 = lm(price ~ total.area + dorms
             + parking + toilets, data = dados)
kable(round(vif(modelo1),2), caption = "VIF com todas as variáveis")
```


```{r, message = FALSE, warning = FALSE, echo=FALSE}
# Removendo toilets
modelo2 = lm(price ~ total.area + dorms
             + parking, data = dados)
kable(round(vif(modelo2),2), caption = "VIF sem toilets")
```


## StepAIC

```{r, message = FALSE, warning = FALSE, echo=FALSE}
selecao = stepAIC(modelo2, direction = "backward")
```


## Modelo

```{r, message = FALSE, warning = FALSE, echo=FALSE}
modelo3 = lm(selecao$call, data = dados)

resultado = summary(modelo3)

kable(round(resultado$coefficients,2), caption = "Resultados finais")
```

## Gráfico de dispersão


```{r message = FALSE, warning = FALSE, echo=FALSE}
dados <- read_excel("todososimoveiseditado.xlsx")[,4:13] 

dados$dorms = NULL
dados$toilets = NULL
dados$parking = NULL
dados$address = NULL
dados$lat = NULL
dados$lng = NULL

dados = drop_na(dados)

# Calcule as médias por bairro
dados_agrupados <- dados %>%
  group_by(Bairro) %>%
  summarise_at(vars(price, `total area`), mean)

dados_agrupados$media_preco = dados_agrupados$price
dados_agrupados$media_area = dados_agrupados$`total area`

# Selecione os top 10 bairros com maiores prices
top_10_bairros <- dados_agrupados %>%
  arrange(desc(media_preco)) %>%
  filter(Bairro != 'Higienópolis') %>%
  head(6)

# Crie o gráfico de barras
paleta_cores = brewer.pal(9, "Blues")

ggplot(top_10_bairros, aes(x = Bairro, y = media_area, fill = media_area)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  scale_fill_viridis_c() +
  labs(title = "Média de prices e Área Total por Bairro",
       x = "Bairro",
       y = "Média de Área Total") +
  theme_minimal() +
  theme(legend.position = "none") +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE))
```


## Clusterização

```{r, message = FALSE, warning = FALSE, echo=FALSE}
library(cluster)

dados3 <- read_excel("todososimoveiseditado.xlsx")[,4:13] 

dados3$dorms = NULL
dados3$toilets = NULL
dados3$parking = NULL
dados3$address = NULL
dados3$lat = NULL
dados3$lng = NULL

dados3 = drop_na(dados3)

dados_cluster <- dados3[, c("Type", "price")]

mapeamento = c("Casa" = 1, "Predio" = 2, "Terreno" = 3, "Apartamento" = 4)

dados_cluster$Type = mapeamento[dados3$Type]

dados_cluster = scale(dados_cluster)

distancia = dist(dados_cluster)

h = hclust(distancia, method = "complete")

plot(h, ylab = "Distancia euclidiana")
rect.hclust(h, k = 5)
```

```{r, , message = FALSE, warning = FALSE, echo=FALSE}
grupos = kmeans(dados_cluster, 5) # quantos clusters?

dados3$cluster = grupos$cluster # associa o numero do cluster aos dados

# library(cluster)
clusplot(dados3, grupos$cluster, color=TRUE, shade=TRUE, labels=2, lines=0, main = "Clustering")
```