---
title: "Lista de Exercicios 1"
author: "Guilherme"
date: "`r Sys.Date()`"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(knitr)
```


Resolucaoo dos Exercicios
===================================== 

Row
-------------------------------------

### Resolucao

- Leitura inicial dos dados

```{r}
dados <- read_xlsx("fonte_lista1.xlsx")
```

- Item `a` 

```{r}
resp_a = dados %>% 
  select(`Week (2008-2009)`, 
         Period, 
         `Avg. Time on Site (secs.)`, 
         Profit)

resp_a %>%
  head(10) %>%
  kable()
```

- Item `b` 

```{r}
resp_b = rename(resp_a, 
                "Semana" = `Week (2008-2009)`, 
                "Periodo" = Period, 
                "Tempo_no_site" = `Avg. Time on Site (secs.)`, 
                "Lucro" = Profit)

resp_b %>%
  head(10) %>%
  kable()
```

- Item `c` 

```{r}
resp_c = resp_b
ordem_valores_periodo = c("Shakedown", "Analysis 1", "Promotion", "Analysis 2")

resp_c$Periodo = factor(resp_b$Periodo, levels=ordem_valores_periodo)

resp_c %>%
  head(10) %>%
  kable()
```

Column
-------------------------------------

- Item `d` 

```{r}
resp_d = resp_c %>%
  ggplot(aes(x=Tempo_no_site, y=Lucro, color=Periodo)) + 
  geom_point(
      size=4,
      alpha=0.6) +
  labs(
    title = "Grafico de dispersao do Tempo medio no site pelo Lucro", 
    y = "Lucro",
    x ="Tempo medio") +
  theme_classic()

resp_d
```

- Item `e` 

```{r}
resp_e = ggplot(resp_c, aes(x=Periodo, y=Lucro, fill=Periodo)) + 
  geom_boxplot() +
  labs(
    title = "Grafico de boxplot do Periodo por lucro", 
    x="Periodo",
    y="Lucro") +
  scale_fill_brewer(palette="Greys") +
  theme_classic()

resp_e
```


Dashboard final
===================================== 

```{r, echo=FALSE}
# Reactive that returns the whole dataset if there is no brush
selectedData <- reactive({
  data <- brushedPoints(resp_c, input$plot_brush)
  if (nrow(data) == 0)
    data <- resp_c
  data
})
```

Column {data-width=300}
-----------------------------------------------------------------------

### Grafico de dispersao do Tempo medio no site pelo Lucro

```{r, echo=FALSE}
renderPlot({
  ggplot(resp_c, aes(x=Tempo_no_site, y=Lucro, color=Periodo)) + 
  geom_point(
      size=4,
      alpha=0.6) +
  labs(
    title = "Grafico de dispersao do Tempo medio no site pelo Lucro", 
    y = "Lucro",
    x ="Tempo medio") +
  theme_classic()
}, outputArgs = list(brush = brushOpts(id = "plot_brush")))
```

### Grafico de boxplot do Periodo por lucro

```{r, echo=FALSE}
renderPlot({
  ggplot(selectedData(), aes(y=Lucro, x=Periodo, fill=Periodo)) + 
  geom_boxplot() +
  labs(
    title = "Grafico de boxplot do Periodo por lucro", 
    x="Periodo",
    y="Lucro") +
  scale_fill_brewer(palette="Greys") +
  theme_classic()
})

```

Column {data-width=400}
-----------------------------------------------------------------------

### Detalhes

```{r, echo=FALSE}
renderTable({
  selectedData()
})
```